name: riverpod_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  go_router: ^10.0.0
  random_name_generator: ^1.1.0
  riverpod_annotation: ^2.1.2
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0


flutter:

  uses-material-design: true

